sudo: false
dist: bionic
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10"
  - "12"
jobs:
  include:
    - stage: npm release
      if: branch = master AND type != pull_request
      node_js: '10'
      script:
        - npx semantic-release
branches:
  only:
    - master
